package UI;

import Core.GestionTorneo;
import Core.Validaciones;
import database.Ccontrol;
import javax.swing.JOptionPane;

/**
 *
 * @authors Fernando Delgado & Daniel Brenes
 */
public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnResultados = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnResultados1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCerrarRegistros = new javax.swing.JButton();
        jtfnickname = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jtfCode = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnRegistro = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnResultados.setBackground(new java.awt.Color(255, 255, 204));
        btnResultados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResultados.setForeground(new java.awt.Color(51, 51, 51));
        btnResultados.setText("Ver Resultados Actuales");
        btnResultados.setBorder(null);
        btnResultados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });
        jPanel2.add(btnResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 210, 29));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocation(new java.awt.Point(450, 200));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Iniciar sesion");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 300, -1));

        jPanel4.setBackground(new java.awt.Color(153, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnResultados1.setBackground(new java.awt.Color(255, 255, 204));
        btnResultados1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResultados1.setForeground(new java.awt.Color(51, 51, 51));
        btnResultados1.setText("Ver Resultados Actuales");
        btnResultados1.setBorder(null);
        btnResultados1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResultados1.setEnabled(false);
        btnResultados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultados1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnResultados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 210, 29));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trofeo.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, -1));

        btnCerrarRegistros.setBackground(new java.awt.Color(204, 0, 0));
        btnCerrarRegistros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrarRegistros.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarRegistros.setText("Cerrar Inscripciones");
        btnCerrarRegistros.setBorder(null);
        btnCerrarRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarRegistrosActionPerformed(evt);
            }
        });
        jPanel4.add(btnCerrarRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 170, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 250, 400));

        jtfnickname.setBackground(new java.awt.Color(255, 255, 255));
        jtfnickname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtfnickname.setForeground(new java.awt.Color(0, 0, 0));
        jtfnickname.setText("Nickname");
        jtfnickname.setBorder(null);
        jtfnickname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfnicknameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfnicknameMousePressed(evt);
            }
        });
        jtfnickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnicknameActionPerformed(evt);
            }
        });
        jPanel3.add(jtfnickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 273, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 290, 10));

        jtfCode.setBackground(new java.awt.Color(255, 255, 255));
        jtfCode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtfCode.setForeground(new java.awt.Color(0, 0, 0));
        jtfCode.setText("Codigo de ingreso");
        jtfCode.setBorder(null);
        jtfCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodeFocusLost(evt);
            }
        });
        jtfCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfCodeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfCodeMousePressed(evt);
            }
        });
        jtfCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodeActionPerformed(evt);
            }
        });
        jPanel3.add(jtfCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 273, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 290, 10));

        btnRegistro.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(51, 51, 51));
        btnRegistro.setText("¿No tienes Cuenta? Registrate");
        btnRegistro.setBorder(null);
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 240, 29));

        btnvolver.setBackground(new java.awt.Color(255, 0, 0));
        btnvolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnvolver.setForeground(new java.awt.Color(0, 0, 0));
        btnvolver.setText("Volver");
        btnvolver.setBorder(null);
        btnvolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        jPanel3.add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 90, 40));

        btnIniciar.setBackground(new java.awt.Color(255, 153, 51));
        btnIniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(0, 0, 0));
        btnIniciar.setText("Iniciar");
        btnIniciar.setBorder(null);
        btnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel3.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed

    }//GEN-LAST:event_btnResultadosActionPerformed

    private void btnResultados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultados1ActionPerformed
        //Creacion de un objeto de la clase Resultados
        Resultados resul = new Resultados();
        dispose();
        resul.show(true);
    }//GEN-LAST:event_btnResultados1ActionPerformed

    private void jtfnicknameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfnicknameMouseClicked
        if (jtfnickname.getText().equals("") || jtfnickname.getText().equals("Nickname")) {
            jtfnickname.setText("");
        }
        if (jtfCode.getText().equals("")) {
            jtfCode.setText("Codigo de ingreso");
        }
    }//GEN-LAST:event_jtfnicknameMouseClicked

    private void jtfnicknameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfnicknameMousePressed
        if (jtfnickname.getText().equals("") || jtfnickname.getText().equals("Nickname")) {
            jtfnickname.setText("");
        }
    }//GEN-LAST:event_jtfnicknameMousePressed

    private void jtfnicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnicknameActionPerformed

    }//GEN-LAST:event_jtfnicknameActionPerformed

    private void jtfCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodeFocusLost

    }//GEN-LAST:event_jtfCodeFocusLost

    private void jtfCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfCodeMouseClicked
        if (jtfCode.getText().equals("") || jtfCode.getText().equals("Codigo de ingreso")) {
            jtfCode.setText("");
        }
        if (jtfnickname.getText().equals("")) {
            jtfnickname.setText("Nickname");
        }
    }//GEN-LAST:event_jtfCodeMouseClicked

    private void jtfCodeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfCodeMousePressed
        if (jtfCode.getText().equals("") || jtfCode.getText().equals("Codigo de ingreso")) {
            jtfCode.setText("");
        }
        if (jtfnickname.getText().equals("")) {
            jtfnickname.setText("Nickname");
        }
    }//GEN-LAST:event_jtfCodeMousePressed

    private void jtfCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodeActionPerformed

    }//GEN-LAST:event_jtfCodeActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        Registro registro = new Registro();
        //Cierra la ventana actual y abre la de registro
        dispose();
        registro.show();
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        dispose();
        //Cierra el Login y envia un mensaje de despedida
        JOptionPane.showMessageDialog(null, "Gracias por usar el programa");
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // Obtener los datos ingresados por el usuario desde los campos de texto
        String nickname = jtfnickname.getText();
        String codigoA = jtfCode.getText();;

        //Creacion de la instancia para la clase de Ccontrol y validaciones
        Ccontrol ccontrol = new Ccontrol();
        Validaciones vali = new Validaciones();
        //Valida si el texto ingresado en jtfCode es un numero entero
        if (vali.esInt(codigoA)) {
            //Convierte el numero a un int
            int codigoAcceso = Integer.parseInt(codigoA);
            //Envio de los datos a la clase ccontrol
            ccontrol.validarUsuario(nickname, codigoAcceso);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el codigo de acceso unicamente con numeros");

        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        //Creditos
        JOptionPane.showMessageDialog(null, "Programa creado por Fernando Delgado & Daniel Brenes \n"
                + "Para la clase de Programacion III (Universidad Latina de Costa Rica)\n"
                + "San Jose, Costa Rica, 2023");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnCerrarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarRegistrosActionPerformed
        String codigocierre = JOptionPane.showInputDialog("Por favor ingrese el código de administrador");
        if (codigocierre == null) {
            //Si presiona cancelar entonces que no haga nada
            return;
        }
        if (codigocierre.equals("4875")) {
            cierreinscripcion();
        } else {
            JOptionPane.showMessageDialog(null, "El codigo de administrador es incorrecto");
        }
    }//GEN-LAST:event_btnCerrarRegistrosActionPerformed

    //Metodo que oculta los botones 
    public void cierreinscripcion() {
        btnCerrarRegistros.setVisible(false);
        btnRegistro.setEnabled(false);
        btnResultados1.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarRegistros;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnResultados;
    private javax.swing.JButton btnResultados1;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jtfCode;
    private javax.swing.JTextField jtfnickname;
    // End of variables declaration//GEN-END:variables
}
