package UI;

import Core.Validaciones;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando Delgado & Daniel Brenes
 */
public class Registro extends javax.swing.JFrame {

    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCondiciones = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfCedula = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jtfApellido = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jtfEmail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jtfResidencia = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jtfNickname = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jcbdia = new javax.swing.JComboBox<>();
        jcbmes = new javax.swing.JComboBox<>();
        jcbyear = new javax.swing.JComboBox<>();
        btnregistro = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setLocation(new java.awt.Point(400, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Snake.png.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Campeonato");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 220, 70));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("del juego del Snake");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        btnCondiciones.setBackground(new java.awt.Color(204, 102, 0));
        btnCondiciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCondiciones.setForeground(new java.awt.Color(0, 0, 0));
        btnCondiciones.setText("Privacidad y condiciones");
        btnCondiciones.setBorder(null);
        btnCondiciones.setBorderPainted(false);
        btnCondiciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCondiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCondicionesActionPerformed(evt);
            }
        });
        jPanel2.add(btnCondiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 340, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Registrarse");

        jtfCedula.setBackground(new java.awt.Color(255, 255, 255));
        jtfCedula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfCedula.setForeground(new java.awt.Color(0, 0, 0));
        jtfCedula.setText("Cedula");
        jtfCedula.setBorder(null);
        jtfCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCedulaFocusLost(evt);
            }
        });
        jtfCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfCedulaMousePressed(evt);
            }
        });
        jtfCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCedulaActionPerformed(evt);
            }
        });

        jtfNombre.setBackground(new java.awt.Color(255, 255, 255));
        jtfNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfNombre.setForeground(new java.awt.Color(0, 0, 0));
        jtfNombre.setText("Nombre");
        jtfNombre.setBorder(null);
        jtfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNombreFocusLost(evt);
            }
        });
        jtfNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfNombreMousePressed(evt);
            }
        });
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N

        jtfApellido.setBackground(new java.awt.Color(255, 255, 255));
        jtfApellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfApellido.setForeground(new java.awt.Color(0, 0, 0));
        jtfApellido.setText("Apellido");
        jtfApellido.setBorder(null);
        jtfApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfApellidoFocusLost(evt);
            }
        });
        jtfApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfApellidoMousePressed(evt);
            }
        });
        jtfApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfApellidoActionPerformed(evt);
            }
        });

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N

        jtfEmail.setBackground(new java.awt.Color(255, 255, 255));
        jtfEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfEmail.setForeground(new java.awt.Color(0, 0, 0));
        jtfEmail.setText("Email");
        jtfEmail.setBorder(null);
        jtfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEmailFocusLost(evt);
            }
        });
        jtfEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfEmailMousePressed(evt);
            }
        });
        jtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmailActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N

        jtfResidencia.setBackground(new java.awt.Color(255, 255, 255));
        jtfResidencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfResidencia.setForeground(new java.awt.Color(0, 0, 0));
        jtfResidencia.setText("Lugar de Residencia");
        jtfResidencia.setBorder(null);
        jtfResidencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfResidenciaFocusLost(evt);
            }
        });
        jtfResidencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfResidenciaMousePressed(evt);
            }
        });
        jtfResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfResidenciaActionPerformed(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N

        jtfNickname.setBackground(new java.awt.Color(255, 255, 255));
        jtfNickname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfNickname.setForeground(new java.awt.Color(0, 0, 0));
        jtfNickname.setText("Nickname");
        jtfNickname.setBorder(null);
        jtfNickname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNicknameFocusLost(evt);
            }
        });
        jtfNickname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfNicknameMousePressed(evt);
            }
        });
        jtfNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNicknameActionPerformed(evt);
            }
        });

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Fecha de nacimiento");

        jcbdia.setBackground(new java.awt.Color(255, 255, 255));
        jcbdia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbdia.setForeground(new java.awt.Color(0, 0, 0));
        jcbdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jcbdia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbdiaActionPerformed(evt);
            }
        });

        jcbmes.setBackground(new java.awt.Color(255, 255, 255));
        jcbmes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbmes.setForeground(new java.awt.Color(0, 0, 0));
        jcbmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jcbmes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jcbyear.setBackground(new java.awt.Color(255, 255, 255));
        jcbyear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbyear.setForeground(new java.awt.Color(0, 0, 0));
        jcbyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923" }));
        jcbyear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbyearActionPerformed(evt);
            }
        });

        btnregistro.setBackground(new java.awt.Color(255, 153, 51));
        btnregistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnregistro.setForeground(new java.awt.Color(0, 0, 0));
        btnregistro.setText("Registrar");
        btnregistro.setBorder(null);
        btnregistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroActionPerformed(evt);
            }
        });

        btnvolver.setBackground(new java.awt.Color(255, 0, 0));
        btnvolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnvolver.setForeground(new java.awt.Color(0, 0, 0));
        btnvolver.setText("Volver");
        btnvolver.setBorder(null);
        btnvolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 391, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jtfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jtfResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jtfNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jcbdia, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(jcbmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(jcbyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(160, 160, 160)
                            .addComponent(btnregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(90, Short.MAX_VALUE)
                    .addComponent(jtfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jtfResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jtfNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(jLabel1)
                    .addGap(5, 5, 5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jcbdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(38, 38, 38)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 20, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCedulaFocusLost
        if (jtfCedula.getText().equals("")) {
            jtfCedula.setText("Cedula");
        }
    }//GEN-LAST:event_jtfCedulaFocusLost

    private void jtfCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfCedulaMousePressed
        // TODO add your handling code here:
        if (jtfCedula.getText().equals("") || jtfCedula.getText().equals("Cedula")) {
            jtfCedula.setText("");
        }
    }//GEN-LAST:event_jtfCedulaMousePressed

    private void jtfCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCedulaActionPerformed

    private void jtfNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNombreFocusLost
        if (jtfNombre.getText().equals("")) {
            jtfNombre.setText("Nombre");
        }
    }//GEN-LAST:event_jtfNombreFocusLost

    private void jtfNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNombreMousePressed
        if (jtfNombre.getText().equals("") || jtfNombre.getText().equals("Nombre")) {
            jtfNombre.setText("");
        }
    }//GEN-LAST:event_jtfNombreMousePressed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jtfApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfApellidoFocusLost
        if (jtfApellido.getText().equals("")) {
            jtfApellido.setText("Apellido");
        }
    }//GEN-LAST:event_jtfApellidoFocusLost

    private void jtfApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfApellidoMousePressed
        if (jtfApellido.getText().equals("") || jtfApellido.getText().equals("Apellido")) {
            jtfApellido.setText("");
        }
    }//GEN-LAST:event_jtfApellidoMousePressed

    private void jtfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfApellidoActionPerformed
        if (jtfApellido.getText().equals("") || jtfNickname.getText().equals("Apellido")) {
            jtfApellido.setText("");
        }
    }//GEN-LAST:event_jtfApellidoActionPerformed

    private void jtfEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfEmailMousePressed
        if (jtfEmail.getText().equals("") || jtfEmail.getText().equals("Email")) {
            jtfEmail.setText("");
        }
    }//GEN-LAST:event_jtfEmailMousePressed

    private void jtfResidenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfResidenciaMousePressed
        if (jtfResidencia.getText().equals("") || jtfResidencia.getText().equals("Lugar de Residencia")) {
            jtfResidencia.setText("");
        }
    }//GEN-LAST:event_jtfResidenciaMousePressed

    private void jtfNicknameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfNicknameMousePressed
        if (jtfNickname.getText().equals("") || jtfNickname.getText().equals("Nickname")) {
            jtfNickname.setText("");
        }
    }//GEN-LAST:event_jtfNicknameMousePressed

    private void jcbdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbdiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbdiaActionPerformed

    private void jcbyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbyearActionPerformed

    private void btnregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroActionPerformed
        Validaciones vali = new Validaciones();
        String cedulaR = jtfCedula.getText();

        if (vali.esInt(cedulaR)) {
            comprobacionDB();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la cedula con numeros y sin guiones");
        }

    }//GEN-LAST:event_btnregistroActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        Login login = new Login();
        dispose();
        login.show(true);
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btnCondicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCondicionesActionPerformed
        JOptionPane.showMessageDialog(null, "Al participar en este campeonato, aceptas los siguientes términos y condiciones: \n"
                + "Edad Minima requerida:\n"
                + "Todos los participantes deben ser mayores de 18 años para poder inscribirse y participar en este campeonato.\n", "Términos y Condiciones", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnCondicionesActionPerformed

    private void jtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmailActionPerformed
        if (jtfEmail.getText().equals("")) {
            jtfEmail.setText("Email");
        }
    }//GEN-LAST:event_jtfEmailActionPerformed

    private void jtfResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfResidenciaActionPerformed
        if (jtfResidencia.getText().equals("")) {
            jtfResidencia.setText("Lugar de Residencia");
        }
    }//GEN-LAST:event_jtfResidenciaActionPerformed

    private void jtfNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNicknameActionPerformed
        if (jtfNickname.getText().equals("")) {
            jtfNickname.setText("Nickname");
        }
    }//GEN-LAST:event_jtfNicknameActionPerformed

    private void jtfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEmailFocusLost
        if (jtfEmail.getText().equals("")) {
            jtfEmail.setText("Email");
        }
    }//GEN-LAST:event_jtfEmailFocusLost

    private void jtfResidenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfResidenciaFocusLost
        if (jtfResidencia.getText().equals("")) {
            jtfResidencia.setText("Lugar de Residencia");
        }
    }//GEN-LAST:event_jtfResidenciaFocusLost

    private void jtfNicknameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNicknameFocusLost
        if (jtfNickname.getText().equals("")) {
            jtfNickname.setText("Nickname");
        }
    }//GEN-LAST:event_jtfNicknameFocusLost

    public void comprobacionDB() {
        database.Clogin objetoLogin = new database.Clogin();
        Random random = new Random();

        String cedula = jtfCedula.getText();
        String nombre = jtfNombre.getText();
        String apellido = jtfApellido.getText();
        String email = jtfEmail.getText();
        String residencia = jtfResidencia.getText();
        String nickname = jtfNickname.getText();
        String dia = (String) jcbdia.getSelectedItem();
        String mes = (String) jcbmes.getSelectedItem();
        String anio = (String) jcbyear.getSelectedItem();

        int diaS = 0;
        int anioS = 0;
        int cedulaS = 0;
        int codigoParticipacion = 0;

        if (cedula.equals("Cedula") || nombre.equals("Nombre") || apellido.equals("Apellido") || email.equals("Email") || residencia.equals("Lugar de Residencia") || nickname.equals("Nickname")) {
            JOptionPane.showMessageDialog(null, "Ingrese datos válidos");
        } else {
            if (dia.equals("Dia") || mes.equals("Mes") || anio.equals("Año")) {
                JOptionPane.showMessageDialog(null, "Seleccione un día, mes y año válidos.");
            } else {
                diaS = Integer.parseInt(dia);
                anioS = Integer.parseInt(anio);
                cedulaS = Integer.parseInt(cedula);
                if (anioS <= 2005) {
                    codigoParticipacion = random.nextInt(9999) + 1; // Genera un número aleatorio entre 1 y 9999
                    objetoLogin.registrarUsuarioNuevo(nickname, nombre, apellido, email, residencia, diaS, mes, anioS, cedulaS, codigoParticipacion);
                } else {
                    JOptionPane.showMessageDialog(null, "El participante no cumple con la edad requerida para participar");
                    codigoParticipacion = 0;
                    objetoLogin.registrarUsuarioNuevo(nickname, nombre, apellido, email, residencia, diaS, mes, anioS, cedulaS, codigoParticipacion);
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCondiciones;
    private javax.swing.JButton btnregistro;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JComboBox<String> jcbdia;
    private javax.swing.JComboBox<String> jcbmes;
    private javax.swing.JComboBox<String> jcbyear;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfCedula;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNickname;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfResidencia;
    // End of variables declaration//GEN-END:variables
}
