package UI;

import Core.Resultado;
import database.Ccontrol;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @authors Fernando Delgado & Daniel Brenes
 */
public class Resultados extends javax.swing.JFrame {

    public Resultados() {
        initComponents();
        actualizarResultados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jlblPuesto3 = new javax.swing.JLabel();
        jlblPuesto1 = new javax.swing.JLabel();
        jlblPuesto2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblRanking = new javax.swing.JTable();
        btnvolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resultados Actuales");
        setLocation(new java.awt.Point(500, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setText("Ranking actual");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 250, -1));

        jlblPuesto3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblPuesto3.setForeground(new java.awt.Color(0, 0, 0));
        jlblPuesto3.setText("Puesto 3");
        jPanel1.add(jlblPuesto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 140, -1));

        jlblPuesto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblPuesto1.setForeground(new java.awt.Color(0, 0, 0));
        jlblPuesto1.setText("Puesto 1");
        jPanel1.add(jlblPuesto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 140, -1));

        jlblPuesto2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblPuesto2.setForeground(new java.awt.Color(0, 0, 0));
        jlblPuesto2.setText("Puesto 2");
        jPanel1.add(jlblPuesto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, -1));

        jtblRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ranking", "Nickname", "Puntuacion", "Tiempo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtblRanking);
        if (jtblRanking.getColumnModel().getColumnCount() > 0) {
            jtblRanking.getColumnModel().getColumn(0).setResizable(false);
            jtblRanking.getColumnModel().getColumn(1).setResizable(false);
            jtblRanking.getColumnModel().getColumn(2).setResizable(false);
            jtblRanking.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 440, 190));

        btnvolver.setBackground(new java.awt.Color(255, 0, 0));
        btnvolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnvolver.setForeground(new java.awt.Color(0, 0, 0));
        btnvolver.setText("Volver");
        btnvolver.setBorder(null);
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 90, 40));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 140, 80));

        jPanel3.setBackground(new java.awt.Color(153, 102, 0));
        jPanel3.setForeground(new java.awt.Color(153, 102, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(67, 67, 67))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 150, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(55, 55, 55))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 140, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        Login login = new Login();
        dispose();
        login.show(true);
        login.cierreinscripcion();
    }//GEN-LAST:event_btnvolverActionPerformed

    public void actualizarResultados() {
        Ccontrol clogin = new Ccontrol();

        //Obtiene los resultados de la base de datos
        ArrayList<Resultado> resultados = clogin.obtenerResultados();

        //Filtra los resultados que tengan puntuación igual a -2
        resultados.removeIf(resultado -> resultado.getPuntuacion() == -2);

        //Ordena los resultados por puntuación de manera descendente
        Collections.sort(resultados, (r1, r2) -> Integer.compare(r2.getPuntuacion(), r1.getPuntuacion()));

        DefaultTableModel model = (DefaultTableModel) jtblRanking.getModel();
        model.setRowCount(0); //Limpiar la tabla antes de agregar datos nuevos

        int puesto = 0; //Variable para controlar el podio

        //Agrega los datos de los resultados a la tabla
        for (Resultado resultado : resultados) {
            puesto++;
            //Si la puntuación es -1, escribe "En espera" en vez de la puntuación
            String puntuacion = (resultado.getPuntuacion() == -1) ? "En espera" : String.valueOf(resultado.getPuntuacion());
            int tiempo = resultado.getTiempo(); //Obtiene el tiempo del participante
            model.addRow(new Object[]{puesto, resultado.getNickname(), puntuacion, tiempo});
        }

        //Muestra los primeros tres puestos si hay suficientes registros
        if (puesto >= 1) {
            jlblPuesto1.setText(resultados.get(0).getNickname());
        } else {
            jlblPuesto1.setText("Puesto 1");
        }
        if (puesto >= 2) {
            jlblPuesto2.setText(resultados.get(1).getNickname());
        } else {
            jlblPuesto2.setText("Puesto 2");
        }
        if (puesto >= 3) {
            jlblPuesto3.setText(resultados.get(2).getNickname());
        } else {
            jlblPuesto3.setText("Puesto 3");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlblPuesto1;
    private javax.swing.JLabel jlblPuesto2;
    private javax.swing.JLabel jlblPuesto3;
    private javax.swing.JTable jtblRanking;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
